### ISSUE TITLE
This seems can not pass https://bot.sannysoft.com/ test？

### ISSUE THREAD

**Issue by youngformax** [mabinogi233/UndetectedChromedriver#4]
I copy your code to my project,and run it navigate to https://bot.sannysoft.com/, but the 'Fingerprint Scanner tests' is show anything,When doing automated crawler testing, the server status returned by the other party's interface is abnormal, but when I use the Python version of UndetectedChromedriver, it is normal.Is me anywhere not right?Can you help me?
```kotlin
fun init() {
    chromeDriver = ChromeDriverBuilder().build(ChromeOptions(), driverHome,true,true)
    chromeDriver.get("https://bot.sannysoft.com/")
    chromeDriverService = ChromeDriverService.Builder().usingDriverExecutable(File(driverHome)).build()
    chromeDriverService.start()
}
```
![image](https://github.com/mabinogi233/UndetectedChromedriver/assets/65012404/6d5f1542-f8e3-407b-84f6-5761c31195ac)

**Comment by mabinogi233** [comment]
![image](https://github.com/mabinogi233/UndetectedChromedriver/assets/51489138/35667549-6804-40e4-9f66-fde53abc04cc)

When I use it is the question not occurred, so I think this problem may be caused by the chrome version.

**Comment by young-kingdom** [comment]
Thanks.it's my wrong,i push wrong params.there's another question,what does function `_cdc Props` in class Undetected_ChromeDriver do?After calling this method, using Chromedriver.get() will delay the welcome interface for a few seconds before navigate to the url.

**Comment by mabinogi233** [comment]
The cdp command is used to issue commands to chromedriver. In UndetectedChromedriver, it is mainly used to modify the chromedriver environment information under selenium. For more details, you could see UndetectedChromedriver.java class.

**Comment by young-kingdom** [comment]
Thank for your help!
