### ISSUE TITLE
A lot of "cannot find symbol" compilation errors

### ISSUE THREAD

**Issue by tabatinga0xffff** [mabinogi233/UndetectedChromedriver#8]
On **Java 11** -- which is required by the project
```
java -version
openjdk version "11.0.22" 2024-01-16
OpenJDK Runtime Environment (build 11.0.22+7)
OpenJDK 64-Bit Server VM (build 11.0.22+7, mixed mode)
```

`mvn compile` or `mvn clean package` produces looooooots of `cannot find symbol` errors. Dozens of them

**Comment by tabatinga0xffff** [comment]
![imagen](https://github.com/mabinogi233/UndetectedChromedriver/assets/143210671/84e0043c-a8dc-4fca-9aad-b90ccc58f34c)

@mabinogi233

**Comment by mabinogi233** [comment]
Because  when I was developing, the selenium version 4.0.0 or above did not exist in the maven repository, so I adding dependencies of selenium version 4.0.0 by manually(It means not use maven). you can manually import the jar package of selenium version 4.0.0 or above to solve this problem.

**Comment by mabinogi233** [comment]
![image](https://github.com/mabinogi233/UndetectedChromedriver/assets/51489138/be35de09-5486-4616-a994-e83f7fe090fb)

If use IDEA you can do this.

**Comment by mabinogi233** [comment]
selenium version > 4.0.0 (must, because when version < 4 selenium can't excute cdp script)

**Comment by tabatinga0xffff** [comment]
**This library** itself doesn't compile. 

Whereas I add "selenium-java" the dependency into my project will be other matter
